version : '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mc536
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
  clj-backend:
    build: ./clj-backend
    environment:
      MYSQL_DATABASE: mc536
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      PORT: 8989
      MYSQL_HOST: mysql
    ports:
      - "8989:8989"
