steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=gcr.io/$PROJECT_ID/mc536-application-$BRANCH_NAME:$COMMIT_SHA
    - --cache=true
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "mc536-application-$BRANCH_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/mc536-application-$BRANCH_NAME:$COMMIT_SHA"
      - "--region"
      - "southamerica-east1"
options:
  logging: CLOUD_LOGGING_ONLY